"""init

Revision ID: 1c4167677f29
Revises: 
Create Date: 2025-09-30 20:34:19.788572

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4167677f29'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executors_name'), 'executors', ['name'], unique=False)
    op.create_table('managers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_name'), 'managers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('executor_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'paid', 'cancelled', 'rejected', name='entry_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_entries_amount_nonnegative'),
    sa.CheckConstraint('char_length(currency) = 3', name='ck_entries_currency_iso_len'),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_currency'), 'entries', ['currency'], unique=False)
    op.create_index(op.f('ix_entries_date'), 'entries', ['date'], unique=False)
    op.create_index(op.f('ix_entries_executor_id'), 'entries', ['executor_id'], unique=False)
    op.create_index(op.f('ix_entries_manager_id'), 'entries', ['manager_id'], unique=False)
    op.create_index('ix_entries_sort', 'entries', ['date', 'id'], unique=False)
    op.create_index(op.f('ix_entries_status'), 'entries', ['status'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_status'), table_name='entries')
    op.drop_index('ix_entries_sort', table_name='entries')
    op.drop_index(op.f('ix_entries_manager_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_executor_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_date'), table_name='entries')
    op.drop_index(op.f('ix_entries_currency'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_managers_name'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_executors_name'), table_name='executors')
    op.drop_table('executors')
    # ### end Alembic commands ###